// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfybhlomdeephlnutfdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmeWJobG9tZGVlcGhsbnV0ZmR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzg3MDMsImV4cCI6MjA3Mjc1NDcwM30.IJW-h7YwYdKn-vV6q_7KEYfy3__3R7Gc-pCVJ621X8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});